DROP TABLE IF EXISTS rdata;
CREATE TABLE rdata (
    id SERIAL PRIMARY KEY,
    a VARCHAR(5) NOT NULL UNIQUE,
    b VARCHAR(5) NOT NULL UNIQUE,
    moment DATE DEFAULT '2020-01-01',
    x NUMERIC(5, 2) CHECK (x > 0));